server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trainigmanagement?serverTimezone=UTC
    username: root
    password: 15111997Taechka
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true

